#pragma config(Sensor, dgtl4,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port8,           Shooter8,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Shooter9,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Shooting()
{



	int last_clicks_left = 0;
	int last_clicks_right = 0;

	while(true)
	{
		motor[Shooter8] = 85;
		motor[Shooter9] = 85;
		//get current
		int current_right_clicks = SensorValue[RightEncoder];
		int current_left_clicks = SensorValue[LeftEncoder];
		//calculate elapsed
		int elapsed_right_clicks = current_right_clicks - last_clicks_right;
		int elapsed_left_clicks = current_left_clicks - last_clicks_left;
		//print
		writeDebugStreamLine("elapsed_right_clicks: %d", elapsed_right_clicks);
		writeDebugStreamLine("elapese_left_clicks: %d", elapsed_left_clicks);
		//save current to last
		last_clicks_left = current_left_clicks;
		last_clicks_right = current_right_clicks;
		delay(100);
	}

}
task main()
{
	startTask(Shooting);

}
