#pragma config(Sensor, dgtl1,  GreenLight,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  YellowLight,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  RedLight,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, FrontLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, BackLED,        sensorLEDtoVCC)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           strafeDrive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftLifter,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightLifter,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HeadLightControlRobotB.c"
#include "DriverJoystickControlRobotB.c"
task main()
{
	SensorType[in1] = sensorNone;
	wait1Msec(1000);
	SensorType[in1]= sensorGyro;
	wait1Msec(2000);

	setHeadLights(strafeMode);

	// User Control
	startTask(controllerPolling);
	startTask(driving);

	while(true)
	{
		delay(105000);
	}
}
