#pragma config(Sensor, dgtl1,  GreenLight,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  YellowLight,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  RedLight,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, FrontLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, BackLED,        sensorLEDtoVCC)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           strafeDrive,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           strafeFront,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           expeller,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shooterLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           shooterRight,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HeadLightControlRobotB.c"
#include "DriverJoystickControlRobotB.c"
task main()
{
 	bLCDBacklight = true;
	displayLCDCenteredString(0, "Calibrating Gyro");
	SensorType[in1] = sensorNone;
	wait1Msec(1000);
	displayLCDCenteredString(1, "50% Complete");
	SensorType[in1]= sensorGyro;
	wait1Msec(2000);
	displayLCDCenteredString(0, "Gyro Ready");
	clearLCDLine(1);
	bLCDBacklight = false;
	setHeadLights(strafeMode);

	// User Control
	startTask(controllerPolling);
	startTask(driving);




	while(true)
	{
		delay(105000);
	}
}
