#pragma config(Sensor, dgtl4,  leftShooter,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  rightShooter,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftTopShooter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightTopShooter, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int shooter_target_speed = 0;

task shooter_power_control()
{
	int last_right_clicks = 0;
	int last_left_clicks = 0;
	int last_read_time = 0;

	while(true)
	{
		int current_right_clicks = SensorValue[rightShooter];
		int current_left_clicks = SensorValue[leftShooter];
		int current_read_time = nPgmTime;

		int elapsed_right_clicks = current_right_clicks - last_right_clicks;
		int elapsed_left_clicks = current_left_clicks - last_left_clicks;
		// int elapsed_time = current_read_time - last_read_time;
		int elapsed_time = 4;

		int current_right_speed = elapsed_right_clicks/elapsed_time;
		int current_left_speed = elapsed_left_clicks/elapsed_time;

			if (current_right_speed < shooter_target_speed)
			{
				motor[rightTopShooter] =  127;
			}
			else if (current_right_speed >= shooter_target_speed)
			{
				motor[rightTopShooter] = 0;
			}
			last_right_clicks = elapsed_right_clicks;

			if (current_left_speed < shooter_target_speed)
			{
				motor[leftTopShooter] = 127;
			}
			else if (current_left_speed >= shooter_target_speed)
			{
				motor[leftTopShooter] = 0;
			}
			last_left_clicks = elapsed_right_clicks;
			last_read_time = current_read_time;

			delay(20);
	}
}


void set_motor_target_speed(int speed){
	// For now, set value and print a debug statement
	shooter_target_speed = speed;
	writeDebugStreamLine("Shooter Target Speed: %d", shooter_target_speed);
}

void adjust_target_speed(int adjustment){
	// For now, adjust value a bit, and print a debug statement
	shooter_target_speed = shooter_target_speed + adjustment;
	writeDebugStreamLine("Shooter Target Speed: %d", shooter_target_speed);
}

// Read Buttons to see if any are pushed
task controllerPolling(){
	while(true){
		// Check each button and do actions
		if(vexRT[Btn8U] == 1){
			// Set motor target speed (Far), Channel 8, Button U
			set_motor_target_speed(127);
			delay(500);
		}
		else if(vexRT[Btn8R] == 1){
			// Set motor target speed (Medium), Channel 8, Button R
			set_motor_target_speed(80);
			delay(500);
		}
		else if(vexRT[Btn8D] == 1){
			// Set motor target speed (Short), Channel 8, Button D
			set_motor_target_speed(30);
			delay(500);
		}
		else if(vexRT[Btn6U] == 1){
			// Adjust motor target speed (5 up), Channel 6, Button U
			adjust_target_speed(5);
			delay(250);
		}
		else if(vexRT[Btn6D] == 1){
			// Adjust motor target speed (5 down), Channel 6, Button D
			adjust_target_speed(-5);
			delay(250);
		}
		else if(vexRT[Btn8L] == 1){
			// Stop all motor speed (0), Channel 8, Button L
			set_motor_target_speed(0);
			delay(500);
		}
		delay(10);
	}
}

// Add driver joystick Controls here
task driving(){
	while(true)
	{

		writeDebugStreamLine("***** Drive Loop ******");
		if((vexRT[Ch2] > 20) || (vexRT[Ch2] < -20))
		{
			writeDebugStreamLine("***** Right Side Go ******");
			motor[rightDrive] = vexRT[Ch2];
		}
		else {
			motor[rightDrive] = 0;
		}

		if((vexRT[Ch3] > 20) || (vexRT[Ch3] < - 20))
		{
			motor[leftDrive] = vexRT[Ch3];
		}
		else {
			motor[leftDrive] = 0;
		}

		delay(50);
	}
}
// End Driver joystick Controls

task main()
{
startTask(shooter_power_control);
startTask(controllerPolling);
startTask(driving);
while(true)
{
delay(100000);
}
}
