#pragma config(Sensor, dgtl1,  GreenLight,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  YellowLight,    sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  RedLight,       sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define GREEN 0
#define YELLOW 1
#define RED 2
#define ALL 3
#define NONE 4

void setRedLight (bool on)
{
	if (on){
		SensorValue[RedLight] = 1;
	}
	else {
		SensorValue[RedLight] = 0;
	}
}

void setYellowLight (bool on)
{
	if (on){
		SensorValue[YellowLight] = 1;
	}
	else {
		SensorValue[YellowLight] = 0;
	}
}
void setGreenLight (bool on)
{
	if (on){
		SensorValue[GreenLight] = 1;
	}
	else {
		SensorValue[GreenLight] = 0;
	}
}

void setStopLight(int color)
{
	if (color==GREEN){
		setRedLight(false);
		setYellowLight(false);
		setGreenLight(true);
	}
	else if (color==YELLOW){
		setRedLight(false);
		setYellowLight(true);
		setGreenLight(false);
	}
	else if (color==RED){
		setRedLight(true);
		setYellowLight(false);
		setGreenLight(false);
	}
	else if (color==ALL){
		setRedLight(true);
		setYellowLight(true);
		setGreenLight(true);
	}
	else if (color==NONE){
		setRedLight(false);
		setYellowLight(false);
		setGreenLight(false);
	}
}

task main()
{
	setStopLight(GREEN);
	delay(2000);
	setStopLight(YELLOW);
	delay(2000);
	setStopLight(RED);
	delay(2000);
	setStopLight(ALL);
	delay(2000);
	setStopLight(NONE);
	delay(2000);


}
